services:
  postgres:
    image: postgres:15-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_DB: postgres  # Оставляем как есть
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank_user -d postgres" ]  # ← Проверяем базу postgres
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-app
    volumes:
      - migration_data:/app/migrations  # Volume для миграций
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres  # ← Подключаемся к postgres
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
      SPRING_LIQUIBASE_ENABLED: "true"
      LOGGING_LEVEL_LIQUIBASE: "ERROR"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_AUTOCONFIGURE_LIQUIBASE: "ERROR"
#      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  migration_data: # Volume для миграций